### ISSUE TITLE
Event "__section__" is not known

### ISSUE THREAD

**Issue by jishvi** [ecoco/magento_profiler#12]
Hi, 
   I got a message saying "'Event '__section__' is not known" when I opened dev.php. 
![screenshot from 2017-01-31 11-42-21](https://cloud.githubusercontent.com/assets/10036266/22454264/7fa1e434-e7aa-11e6-8181-606280f9a9a7.png)

How do I fix this?

**Comment by Fantus** [comment]
Hi,

thx for reporting, can you give me some more details on your magento version?
From your error log it looks like you are using the default magento profiler. Can you disable it and try again?

best
Justus

**Comment by jishvi** [comment]
Hey, 
  I disabled the profiler. Now it's working fine. 
Thanks.
