### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by danielchicote** [ecoco/magento_profiler#21]
Hello i have installed the module via composer, but the dev.php file is an empty file and the installation don't works. When i try to replace or delete it, the system don't have permissions.

How can i remove the module? I have delete the lines from the composer.json file, and when i have update it looks that it works, but composer don't really delete the files.

Thanks.

**Comment by Fantus** [comment]
Hi sorry to hear that it is not working for you. 

can you give me a bit more details about the system you are using?

composer tries to symlink the files, if this does not work you end up with for example an empty "dev.php" file

**Comment by danielchicote** [comment]
Hello i have deleted it with the windows commands.

I don't know why the dev.php and app/code files are always empty when i install the module.

**Comment by Fantus** [comment]
can you do me a favor and try adding:
```        "magento-deploystrategy": "copy",```
under the "extra" node in your composer.json

like this:
``` 
{
    "extra":{
        "magento-deploystrategy": "copy",
     }
}
```

this will disable the use of symlinks and just copy the files, maybe this fixes your issue.

what kind of operating system are you using?
