### ISSUE TITLE
Undefined class constant 'TYPE_DATABASE'

### ISSUE THREAD

**Issue by Kamik** [ecoco/magento_profiler#24]
(1/1) FatalThrowableErrorUndefined class constant 'TYPE_DATABASE'
--
in Profiler.php (line 278)
at Zend_Db_Profiler->queryStart('connect', 1)in Abstract.php (line 116)
at Zend_Db_Adapter_Pdo_Abstract->_connect()in Mysql.php (line 111)
at Zend_Db_Adapter_Pdo_Mysql->_connect()in Mysql.php (line 396)
at Varien_Db_Adapter_Pdo_Mysql->_connect()in Abstract.php (line 460)
at Zend_Db_Adapter_Abstract->query('SET NAMES utf8', array())in Abstract.php (line 238)
at Zend_Db_Adapter_Pdo_Abstract->query('SET NAMES utf8', array())in Mysql.php (line 504)
at Varien_Db_Adapter_Pdo_Mysql->query('SET NAMES utf8')in Original_Mage_Core_Model_Resource-1.3.0-0d494aef71eb1df19e34cdd6581a2092.php (line 179)
at Original_Mage_Core_Model_Resource->_newConnection('pdo_mysql', array('persistent' => '0', 'host' => '127.0.0.1', 'username' => 'xxx', 'password' => 'xxx', 'dbname' => 'xxx', 'initStatements' => 'SET NAMES utf8', 'model' => 'mysql4', 'type' => 'pdo_mysql', 'pdoType' => '', 'active' => '1', 'profiler' => true))in Original_Mage_Core_Model_Resource-1.3.0-0d494aef71eb1df19e34cdd6581a2092.php (line 110)
at Original_Mage_Core_Model_Resource->getConnection('core_write')in MageCoreModelResource.php (line 20)
at Mage_Core_Model_Resource->getConnection('core_write')in Original_Mage_Core_Model_Resource_Db_Abstract-1.3.0-70742e4f98224203c04a01836d23c1c5.php (line 320)
at Original_Mage_Core_Model_Resource_Db_Abstract->_getConnection('write')in Original_Mage_Core_Model_Resource_Db_Abstract-1.3.0-70742e4f98224203c04a01836d23c1c5.php (line 350)
at Original_Mage_Core_Model_Resource_Db_Abstract->_getWriteAdapter()in Original_Mage_Core_Model_Resource_Db_Abstract-1.3.0-70742e4f98224203c04a01836d23c1c5.php (line 335)
at Original_Mage_Core_Model_Resource_Db_Abstract->_getReadAdapter()in Cache.php (line 53)
at Mage_Core_Model_Resource_Cache->getAllOptions()in Cache.php (line 478)
at Mage_Core_Model_Cache->_initOptions()in Cache.php (line 520)
at Mage_Core_Model_Cache->canUse('config')in App.php (line 1202)
at Mage_Core_Model_App->useCache('config')in Config.php (line 417)
at Mage_Core_Model_Config->_canUseCacheForInit()in Config.php (line 297)
at Mage_Core_Model_Config->loadModulesCache()in App.php (line 424)
at Mage_Core_Model_App->_initModules()in App.php (line 354)
at Mage_Core_Model_App->run(array('scope_code' => '', 'scope_type' => 'store', 'options' => array('cache' => array('id_prefix' => 'dev'), 'config_model' => 'Ecocode_Profiler_Model_Core_Config')))in Original_Mage_1.3.0-1f73e46ba1fdc7202d83fb12d0eafb91.php (line 691)
at MageOriginal::run('', 'store', array('cache' => array('id_prefix' => 'dev'), 'config_model' => 'Ecocode_Profiler_Model_Core_Config'))in dev.php (line 59)

**Comment by Fantus** [comment]
Hi, 

it looks like your also using "https://github.com/AOEpeople/Aoe_Profiler/blob/master/app/code/community/Varien/Profiler.php"

Try disable the Aoe_Profiler and try again. I hope this will fix it.

Please let me know if it solves your issue or if you have any other questions.

**Comment by Kamik** [comment]
Magento - 1.9.3.8
Server version: 10.2.15-MariaDB-10.2.15+maria~xenial mariadb.org binary distribution
Magento profiler is disabled in developer options.

**Comment by Fantus** [comment]
I just edited my answer as i noticed your using the Aoe_Profiler. Please try disabling the Aoe_Profiler

**Comment by Kamik** [comment]
yes, thanks. After remove Aoe_Profiler all is ok (disabling module does not help)
