### ISSUE TITLE
Error: Cannot declare class Mage, because the name is already in use

### ISSUE THREAD

**Issue by gustavosolomon** [ecoco/magento_profiler#27]
Hello, how r u?

I'm trying to add the extension to my store, but i've been receiving the following error:

(1/1) FatalErrorException
Error: Cannot declare class Mage, because the name is already in use

What can it be?

🅰️: I have a other(old) autoloader.php on the "original"(default) Mage.php

🅱️: I use MultiClient extension, but there's no relation between 🅰️ and "magento_profiler".

Can you please help me? Thanks a lot :D

**Comment by Fantus** [comment]
Hi,

hard to tell without able to reproduce it. Anyway we can try:
The profiler does create a copy of the `Mage.php` to do some overwrites that are needed for the profiling.
From a first look i would say that somewhere in your code yo do require the original `Mage.php` which would explain this kind of error. Can you provide a full stack trace?

**Comment by gustavosolomon** [comment]
Thanks for response,

I have printed get_declared_classes() right after

> require_once $overwriteBasePath . 'Mage.php';

 and this is what i've got:

  | Array
-- | --
  | (
  | [0] => stdClass
  | [1] => Exception
  | [2] => ErrorException
  | [3] => Error
  | [4] => ParseError
  | [5] => TypeError
  | [6] => ArgumentCountError
  | [7] => ArithmeticError
  | [8] => DivisionByZeroError
  | [9] => Closure
  | [10] => Generator
  | [11] => ClosedGeneratorException
  | [12] => DateTime
  | [13] => DateTimeImmutable
  | [14] => DateTimeZone
  | [15] => DateInterval
  | [16] => DatePeriod
  | [17] => LibXMLError
  | [18] => HashContext
  | [19] => ReflectionException
  | [20] => Reflection
  | [21] => ReflectionFunctionAbstract
  | [22] => ReflectionFunction
  | [23] => ReflectionGenerator
  | [24] => ReflectionParameter
  | [25] => ReflectionType
  | [26] => ReflectionNamedType
  | [27] => ReflectionMethod
  | [28] => ReflectionClass
  | [29] => ReflectionObject
  | [30] => ReflectionProperty
  | [31] => ReflectionClassConstant
  | [32] => ReflectionExtension
  | [33] => ReflectionZendExtension
  | [34] => LogicException
  | [35] => BadFunctionCallException
  | [36] => BadMethodCallException
  | [37] => DomainException
  | [38] => InvalidArgumentException
  | [39] => LengthException
  | [40] => OutOfRangeException
  | [41] => RuntimeException
  | [42] => OutOfBoundsException
  | [43] => OverflowException
  | [44] => RangeException
  | [45] => UnderflowException
  | [46] => UnexpectedValueException
  | [47] => RecursiveIteratorIterator
  | [48] => IteratorIterator
  | [49] => FilterIterator
  | [50] => RecursiveFilterIterator
  | [51] => CallbackFilterIterator
  | [52] => RecursiveCallbackFilterIterator
  | [53] => ParentIterator
  | [54] => LimitIterator
  | [55] => CachingIterator
  | [56] => RecursiveCachingIterator
  | [57] => NoRewindIterator
  | [58] => AppendIterator
  | [59] => InfiniteIterator
  | [60] => RegexIterator
  | [61] => RecursiveRegexIterator
  | [62] => EmptyIterator
  | [63] => RecursiveTreeIterator
  | [64] => ArrayObject
  | [65] => ArrayIterator
  | [66] => RecursiveArrayIterator
  | [67] => SplFileInfo
  | [68] => DirectoryIterator
  | [69] => FilesystemIterator
  | [70] => RecursiveDirectoryIterator
  | [71] => GlobIterator
  | [72] => SplFileObject
  | [73] => SplTempFileObject
  | [74] => SplDoublyLinkedList
  | [75] => SplQueue
  | [76] => SplStack
  | [77] => SplHeap
  | [78] => SplMinHeap
  | [79] => SplMaxHeap
  | [80] => SplPriorityQueue
  | [81] => SplFixedArray
  | [82] => SplObjectStorage
  | [83] => MultipleIterator
  | [84] => SessionHandler
  | [85] => __PHP_Incomplete_Class
  | [86] => php_user_filter
  | [87] => Directory
  | [88] => AssertionError
  | [89] => CURLFile
  | [90] => DOMException
  | [91] => DOMStringList
  | [92] => DOMNameList
  | [93] => DOMImplementationList
  | [94] => DOMImplementationSource
  | [95] => DOMImplementation
  | [96] => DOMNode
  | [97] => DOMNameSpaceNode
  | [98] => DOMDocumentFragment
  | [99] => DOMDocument
  | [100] => DOMNodeList
  | [101] => DOMNamedNodeMap
  | [102] => DOMCharacterData
  | [103] => DOMAttr
  | [104] => DOMElement
  | [105] => DOMText
  | [106] => DOMComment
  | [107] => DOMTypeinfo
  | [108] => DOMUserDataHandler
  | [109] => DOMDomError
  | [110] => DOMErrorHandler
  | [111] => DOMLocator
  | [112] => DOMConfiguration
  | [113] => DOMCdataSection
  | [114] => DOMDocumentType
  | [115] => DOMNotation
  | [116] => DOMEntity
  | [117] => DOMEntityReference
  | [118] => DOMProcessingInstruction
  | [119] => DOMStringExtend
  | [120] => DOMXPath
  | [121] => finfo
  | [122] => PDOException
  | [123] => PDO
  | [124] => PDOStatement
  | [125] => PDORow
  | [126] => PharException
  | [127] => Phar
  | [128] => PharData
  | [129] => PharFileInfo
  | [130] => SimpleXMLElement
  | [131] => SimpleXMLIterator
  | [132] => SoapClient
  | [133] => SoapVar
  | [134] => SoapServer
  | [135] => SoapFault
  | [136] => SoapParam
  | [137] => SoapHeader
  | [138] => SQLite3
  | [139] => SQLite3Stmt
  | [140] => SQLite3Result
  | [141] => XMLWriter
  | [142] => XSLTProcessor
  | [143] => ZipArchive
  | [144] => mysqli_sql_exception
  | [145] => mysqli_driver
  | [146] => mysqli
  | [147] => mysqli_warning
  | [148] => mysqli_result
  | [149] => mysqli_stmt
  | [150] => XMLReader
  | [151] => newrelic\DistributedTracePayload
  | [152] => newrelic\Guzzle4\Subscriber
  | [153] => newrelic\Guzzle6\RequestHandler
  | [154] => newrelic\Laravel\AfterFilter
  | [155] => Redis
  | [156] => RedisArray
  | [157] => RedisCluster
  | [158] => RedisException
  | [159] => RedisClusterException
  | [160] => Ecocoder_Profiler_Autoloader
  | [161] => Ecocoder_Profiler_Helper_Data
  | [162] => MageOriginal
  | [163] => Varien_Autoload
  | [164] => phpseclib_mcrypt_filter
  | [165] => ComposerAutoloaderInit7e83c128dfa33f248cdcb1782d2e3e31
  | [166] => Composer\Autoload\ClassLoader
  | [167] => Composer\Autoload\ComposerStaticInit7e83c128dfa33f248cdcb1782d2e3e31
  | [168] => Mage
  | )
  |  

It would be possible that my composer autoloader is loading Mage.php?

**Comment by beppause-it** [comment]
I have the same problem:


FatalErrorException in Mage.php line 69:
Error: Cannot redeclare class Mage
in Mage.php line 69
in Template.php line 241
at Mage_Core_Block_Template->fetchView() in Template.php line 272
at Mage_Core_Block_Template->renderView() in Template.php line 286
at Mage_Core_Block_Template->_toHtml() in Abstract.php line 923
at Mage_Core_Block_Abstract->toHtml() in Abstract.php line 641
at Mage_Core_Block_Abstract->_getChildHtml() in Abstract.php line 585
at Mage_Core_Block_Abstract->getChildHtml() in 1column.phtml line 57
in Template.php line 241
at Mage_Core_Block_Template->fetchView() in Template.php line 272
at Mage_Core_Block_Template->renderView() in Template.php line 286
at Mage_Core_Block_Template->_toHtml() in Abstract.php line 923
at Mage_Core_Block_Abstract->toHtml() in Layout.php line 555
at Mage_Core_Model_Layout->getOutput() in Action.php line 390
at Mage_Core_Controller_Varien_Action->renderLayout() in Page.php line 137
at Mage_Cms_Helper_Page->_renderPage() in Page.php line 52
at Mage_Cms_Helper_Page->renderPage() in IndexController.php line 45
at Mage_Cms_IndexController->indexAction() in Action.php line 418
at Mage_Core_Controller_Varien_Action->dispatch() in Standard.php line 254
at Mage_Core_Controller_Varien_Router_Standard->match() in Standard.php line 46
at ArtsOnIT_OfflineMaintenance_Controller_Router_Standard->match() in Front.php line 172
at Mage_Core_Controller_Varien_Front->dispatch() in App.php line 365
at Mage_Core_Model_App->run() in Original_Mage_1.3.0-b72543286b3a10cb00b4e2025f8d57a6.php line 692
at MageOriginal::run() in dev.php line 58
at {main}() in dev.php line 0

**Comment by beppause-it** [comment]
PHP Stack trace:
 PHP   1. {main}() ./vendor/ecocode/magento_profiler/dev.php:0
 PHP   2. MageOriginal::run() ./vendor/ecocode/magento_profiler/dev.php:58
 PHP   3. Mage_Core_Model_App->run() ./var/cache/Original_Mage_1.3.0-b72543286b3a10cb00b4e2025f8d57a6.php:692
 PHP   4. Mage_Core_Controller_Varien_Front->dispatch() ./app/code/core/Mage/Core/Model/App.php:365
 PHP   5. ArtsOnIT_OfflineMaintenance_Controller_Router_Standard->match() ./app/code/core/Mage/Core/Controller/Varien/Front.php:172
 PHP   6. Mage_Core_Controller_Varien_Router_Standard->match() ./app/code/community/ArtsOnIT/OfflineMaintenance/Controller/Router/Standard.php:46
 PHP   7. Mage_Core_Controller_Varien_Action->dispatch() ./app/code/core/Mage/Core/Controller/Varien/Router/Standard.php:254
 PHP   8. Mage_Cms_IndexController->indexAction() ./app/code/core/Mage/Core/Controller/Varien/Action.php:418
 PHP   9. Mage_Cms_Helper_Page->renderPage() ./app/code/core/Mage/Cms/controllers/IndexController.php:45
 PHP  10. Mage_Cms_Helper_Page->_renderPage() ./app/code/core/Mage/Cms/Helper/Page.php:52
 PHP  11. Mage_Core_Controller_Varien_Action->renderLayout() ./app/code/core/Mage/Cms/Helper/Page.php:137
 PHP  12. Mage_Core_Model_Layout->getOutput() ./app/code/core/Mage/Core/Controller/Varien/Action.php:390
 PHP  13. Mage_Core_Block_Abstract->toHtml() ./app/code/core/Mage/Core/Model/Layout.php:555
 PHP  14. Mage_Core_Block_Template->_toHtml() ./app/code/core/Mage/Core/Block/Abstract.php:923
 PHP  15. Mage_Core_Block_Template->renderView() ./app/code/core/Mage/Core/Block/Template.php:286
 PHP  16. Mage_Core_Block_Template->fetchView() ./app/code/core/Mage/Core/Block/Template.php:272
 PHP  17. include() ./app/code/core/Mage/Core/Block/Template.php:241
 PHP  18. Mage_Core_Block_Abstract->getChildHtml() ./app/design/frontend/typologancee/ss19/template/page/1column.phtml:57
 PHP  19. Mage_Core_Block_Abstract->_getChildHtml() ./app/code/core/Mage/Core/Block/Abstract.php:585
 PHP  20. Mage_Core_Block_Abstract->toHtml() ./app/code/core/Mage/Core/Block/Abstract.php:641
 PHP  21. Mage_Core_Block_Template->_toHtml() ./app/code/core/Mage/Core/Block/Abstract.php:923
 PHP  22. Mage_Core_Block_Template->renderView() ./app/code/core/Mage/Core/Block/Template.php:286
 PHP  24. include() ./app/code/core/Mage/Core/Block/Template.php:241
 PHP  23. Mage_Core_Block_Template->fetchView() ./app/code/core/Mage/Core/Block/Template.php:272

**Comment by gustavosolomon** [comment]
I've made it! It was caused by relation between modules that also rewrite Mage_Core_Model_Config, then I've created a order of rewrite rule on it. Big Thanks :)
