### ISSUE TITLE
Fatal error on catalog_category_view

### ISSUE THREAD

**Issue by lucalbert** [ecoco/magento_profiler#6]
Hi,

I get the following error when I browse the pages of the category level above 0 (roots categories works fine):

![magento-profiler-error-on-category-page](https://cloud.githubusercontent.com/assets/6500267/19595405/1a010c56-978a-11e6-9bdb-d69f2f074471.png)

**Comment by Fantus** [comment]
Hi lucalbert,

thx for the report, will take a look as soon as possible. still magento 1.9.2.4 right? i guess its not a fresh install?

**Comment by lucalbert** [comment]
Hi Fantus,

Yes, it's always the same version of Magento.

**Comment by Fantus** [comment]
i pushed a fix to the master, please let me know if it worked for you https://github.com/ecoco/magento_profiler/commit/d488d3d67a0a1c68d8c78936d4b18ec6e031ce35

**Comment by lucalbert** [comment]
It works !
